<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0SIBDDD" failures="0" tests="1" name="testcase.EpenTestcaseLogin" time="14.037" errors="1" timestamp="2023-06-28T17:12:10 IST" skipped="0">
  <testcase classname="testcase.EpenTestcaseLogin" name="Login" time="14.037">
    <error message="C:\Users\user\OneDrive\Documents\epenV15\SikuliImages\evaluator1.PNG: (269x49) seen at (633, 383) with 0.75 in R[0,0 1536x864]@S(0)" type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: C:\Users\user\OneDrive\Documents\epenV15\SikuliImages\evaluator1.PNG: (269x49) seen at (633, 383) with 0.75 in R[0,0 1536x864]@S(0)
  Line 2222, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2222)
at org.sikuli.script.Region.wait(Region.java:2240)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3188)
at org.sikuli.script.Region.mouseMove(Region.java:4099)
at testcase.EpenTestcaseLogin.Login(EpenTestcaseLogin.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Login -->
  <system-out/>
</testsuite> <!-- testcase.EpenTestcaseLogin -->
